import {
  Role,
  PaymentStatus,
  ApprovalStatus,
  InvitationStatus,
  type User,
  type Event,
  type Participant,
  type Invitation,
  type Review,
  type Payment,
} from "./types"

// Dummy Users
export const dummyUsers: User[] = [
  {
    id: "user-1",
    full_name: "John Doe",
    email: "john@example.com",
    password: "password123",
    role: Role.USER,
    is_deleted: false,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2023-01-01T00:00:00Z",
  },
  {
    id: "user-2",
    full_name: "Jane Smith",
    email: "jane@example.com",
    password: "password123",
    role: Role.USER,
    is_deleted: false,
    created_at: "2023-01-02T00:00:00Z",
    updated_at: "2023-01-02T00:00:00Z",
  },
  {
    id: "user-3",
    full_name: "Admin User",
    email: "admin@example.com",
    password: "admin123",
    role: Role.ADMIN,
    is_deleted: false,
    created_at: "2023-01-03T00:00:00Z",
    updated_at: "2023-01-03T00:00:00Z",
  },
  {
    id: "user-4",
    full_name: "Alice Johnson",
    email: "alice@example.com",
    password: "password123",
    role: Role.USER,
    is_deleted: false,
    created_at: "2023-01-04T00:00:00Z",
    updated_at: "2023-01-04T00:00:00Z",
  },
  {
    id: "user-5",
    full_name: "Bob Williams",
    email: "bob@example.com",
    password: "password123",
    role: Role.USER,
    is_deleted: false,
    created_at: "2023-01-05T00:00:00Z",
    updated_at: "2023-01-05T00:00:00Z",
  },
]

// Dummy Events
export const dummyEvents: Event[] = [
  {
    id: "event-1",
    title: "Tech Conference 2023",
    description:
      "Join us for the biggest tech conference of the year. Learn from industry experts, network with peers, and discover the latest trends in technology.",
    date_time: "2023-06-15T09:00:00Z",
    venue: "Convention Center, New York",
    is_public: true,
    is_paid: true,
    registration_fee: 99.99,
    organizer_id: "user-1",
    created_at: "2023-01-10T00:00:00Z",
    updated_at: "2023-01-10T00:00:00Z",
    organizer: dummyUsers[0],
  },
  {
    id: "event-2",
    title: "Community Meetup",
    description:
      "Monthly community meetup to discuss local issues and initiatives. Everyone is welcome to join and share their ideas.",
    date_time: "2023-05-20T18:00:00Z",
    venue: "Community Hall, Boston",
    is_public: true,
    is_paid: false,
    registration_fee: 0,
    organizer_id: "user-2",
    created_at: "2023-01-15T00:00:00Z",
    updated_at: "2023-01-15T00:00:00Z",
    organizer: dummyUsers[1],
  },
  {
    id: "event-3",
    title: "Private Networking Dinner",
    description:
      "Exclusive networking dinner for professionals in the finance industry. Connect with potential partners and clients.",
    date_time: "2023-07-10T19:00:00Z",
    venue: "Luxury Hotel, Chicago",
    is_public: false,
    is_paid: true,
    registration_fee: 149.99,
    organizer_id: "user-1",
    created_at: "2023-01-20T00:00:00Z",
    updated_at: "2023-01-20T00:00:00Z",
    organizer: dummyUsers[0],
  },
  {
    id: "event-4",
    title: "Charity Fundraiser",
    description:
      "Annual charity fundraiser to support local education initiatives. All proceeds go directly to schools in need.",
    date_time: "2023-08-05T17:00:00Z",
    venue: "City Park, San Francisco",
    is_public: true,
    is_paid: true,
    registration_fee: 25.0,
    organizer_id: "user-4",
    created_at: "2023-01-25T00:00:00Z",
    updated_at: "2023-01-25T00:00:00Z",
    organizer: dummyUsers[3],
  },
  {
    id: "event-5",
    title: "Book Club Meeting",
    description: "Monthly book club meeting to discuss 'The Great Gatsby'. New members are welcome to join.",
    date_time: "2023-05-25T19:00:00Z",
    venue: "Local Library, Seattle",
    is_public: true,
    is_paid: false,
    registration_fee: 0,
    organizer_id: "user-5",
    created_at: "2023-01-30T00:00:00Z",
    updated_at: "2023-01-30T00:00:00Z",
    organizer: dummyUsers[4],
  },
  {
    id: "event-6",
    title: "Private Workshop: Leadership Skills",
    description: "Intensive workshop on developing leadership skills for mid-level managers. Limited spots available.",
    date_time: "2023-09-15T10:00:00Z",
    venue: "Business Center, Dallas",
    is_public: false,
    is_paid: true,
    registration_fee: 199.99,
    organizer_id: "user-2",
    created_at: "2023-02-05T00:00:00Z",
    updated_at: "2023-02-05T00:00:00Z",
    organizer: dummyUsers[1],
  },
  {
    id: "event-7",
    title: "Photography Exhibition",
    description: "Exhibition showcasing the work of local photographers. Come and appreciate the art of photography.",
    date_time: "2023-07-20T11:00:00Z",
    venue: "Art Gallery, Miami",
    is_public: true,
    is_paid: true,
    registration_fee: 10.0,
    organizer_id: "user-4",
    created_at: "2023-02-10T00:00:00Z",
    updated_at: "2023-02-10T00:00:00Z",
    organizer: dummyUsers[3],
  },
  {
    id: "event-8",
    title: "Yoga in the Park",
    description: "Free yoga session in the park for all skill levels. Bring your own mat and enjoy a relaxing morning.",
    date_time: "2023-06-10T08:00:00Z",
    venue: "Central Park, New York",
    is_public: true,
    is_paid: false,
    registration_fee: 0,
    organizer_id: "user-5",
    created_at: "2023-02-15T00:00:00Z",
    updated_at: "2023-02-15T00:00:00Z",
    organizer: dummyUsers[4],
  },
  {
    id: "event-9",
    title: "Private Music Concert",
    description: "Exclusive concert featuring local bands. Limited tickets available for this intimate venue.",
    date_time: "2023-08-25T20:00:00Z",
    venue: "Small Venue, Austin",
    is_public: false,
    is_paid: false,
    registration_fee: 0,
    organizer_id: "user-1",
    created_at: "2023-02-20T00:00:00Z",
    updated_at: "2023-02-20T00:00:00Z",
    organizer: dummyUsers[0],
  },
]

// Dummy Participants
export const dummyParticipants: Participant[] = [
  {
    id: "participant-1",
    event_id: "event-1",
    user_id: "user-2",
    payment_status: PaymentStatus.PAID,
    approval_status: ApprovalStatus.APPROVED,
    is_banned: false,
    joined_at: "2023-03-01T00:00:00Z",
    user: dummyUsers[1],
  },
  {
    id: "participant-2",
    event_id: "event-1",
    user_id: "user-4",
    payment_status: PaymentStatus.PAID,
    approval_status: ApprovalStatus.APPROVED,
    is_banned: false,
    joined_at: "2023-03-02T00:00:00Z",
    user: dummyUsers[3],
  },
  {
    id: "participant-3",
    event_id: "event-2",
    user_id: "user-1",
    payment_status: PaymentStatus.FREE,
    approval_status: ApprovalStatus.APPROVED,
    is_banned: false,
    joined_at: "2023-03-03T00:00:00Z",
    user: dummyUsers[0],
  },
  {
    id: "participant-4",
    event_id: "event-2",
    user_id: "user-4",
    payment_status: PaymentStatus.FREE,
    approval_status: ApprovalStatus.APPROVED,
    is_banned: false,
    joined_at: "2023-03-04T00:00:00Z",
    user: dummyUsers[3],
  },
  {
    id: "participant-5",
    event_id: "event-3",
    user_id: "user-2",
    payment_status: PaymentStatus.PAID,
    approval_status: ApprovalStatus.APPROVED,
    is_banned: false,
    joined_at: "2023-03-05T00:00:00Z",
    user: dummyUsers[1],
  },
  {
    id: "participant-6",
    event_id: "event-1",
    user_id: "user-5",
    payment_status: PaymentStatus.PENDING,
    approval_status: ApprovalStatus.PENDING,
    is_banned: false,
    joined_at: "2023-03-06T00:00:00Z",
    user: dummyUsers[4],
  },
]

// Dummy Invitations
export const dummyInvitations: Invitation[] = [
  {
    id: "invitation-1",
    event_id: "event-3",
    sender_id: "user-1",
    receiver_id: "user-4",
    is_paid_event: true,
    payment_status: PaymentStatus.PENDING,
    invitation_status: InvitationStatus.PENDING,
    created_at: "2023-04-01T00:00:00Z",
  },
  {
    id: "invitation-2",
    event_id: "event-6",
    sender_id: "user-2",
    receiver_id: "user-1",
    is_paid_event: true,
    payment_status: PaymentStatus.PAID,
    invitation_status: InvitationStatus.ACCEPTED,
    created_at: "2023-04-02T00:00:00Z",
  },
  {
    id: "invitation-3",
    event_id: "event-9",
    sender_id: "user-1",
    receiver_id: "user-5",
    is_paid_event: false,
    payment_status: PaymentStatus.FREE,
    invitation_status: InvitationStatus.DECLINED,
    created_at: "2023-04-03T00:00:00Z",
  },
  {
    id: "invitation-4",
    event_id: "event-3",
    sender_id: "user-1",
    receiver_id: "user-5",
    is_paid_event: true,
    payment_status: PaymentStatus.PENDING,
    invitation_status: InvitationStatus.PENDING,
    created_at: "2023-04-04T00:00:00Z",
  },
]

// Dummy Reviews
export const dummyReviews: Review[] = [
  {
    id: "review-1",
    user_id: "user-2",
    event_id: "event-1",
    rating: 5,
    comment: "Excellent conference! Learned a lot and made great connections.",
    created_at: "2023-06-16T00:00:00Z",
    user: dummyUsers[1],
    event: dummyEvents[0],
  },
  {
    id: "review-2",
    user_id: "user-4",
    event_id: "event-1",
    rating: 4,
    comment: "Great speakers and content. The venue could have been better.",
    created_at: "2023-06-17T00:00:00Z",
    user: dummyUsers[3],
    event: dummyEvents[0],
  },
  {
    id: "review-3",
    user_id: "user-1",
    event_id: "event-2",
    rating: 5,
    comment: "Very productive community meeting. Looking forward to the next one!",
    created_at: "2023-05-21T00:00:00Z",
    user: dummyUsers[0],
    event: dummyEvents[1],
  },
  {
    id: "review-4",
    user_id: "user-2",
    event_id: "event-3",
    rating: 3,
    comment: "The food was amazing but the networking opportunities were limited.",
    created_at: "2023-07-11T00:00:00Z",
    user: dummyUsers[1],
    event: dummyEvents[2],
  },
]

// Dummy Payments
export const dummyPayments: Payment[] = [
  {
    id: "payment-1",
    user_id: "user-2",
    event_id: "event-1",
    amount: 99.99,
    status: PaymentStatus.PAID,
    method: "Credit Card",
    transaction_id: "txn_123456",
    gateway_data: { processor: "Stripe" },
    paid_at: "2023-03-01T00:00:00Z",
    user: dummyUsers[1],
    event: dummyEvents[0],
  },
  {
    id: "payment-2",
    user_id: "user-4",
    event_id: "event-1",
    amount: 99.99,
    status: PaymentStatus.PAID,
    method: "PayPal",
    transaction_id: "txn_234567",
    gateway_data: { processor: "PayPal" },
    paid_at: "2023-03-02T00:00:00Z",
    user: dummyUsers[3],
    event: dummyEvents[0],
  },
  {
    id: "payment-3",
    user_id: "user-2",
    event_id: "event-3",
    amount: 149.99,
    status: PaymentStatus.PAID,
    method: "Credit Card",
    transaction_id: "txn_345678",
    gateway_data: { processor: "Stripe" },
    paid_at: "2023-03-05T00:00:00Z",
    user: dummyUsers[1],
    event: dummyEvents[2],
  },
  {
    id: "payment-4",
    user_id: "user-5",
    event_id: "event-1",
    amount: 99.99,
    status: PaymentStatus.PENDING,
    method: "Credit Card",
    transaction_id: "txn_456789",
    gateway_data: { processor: "Stripe" },
    paid_at: "2023-03-06T00:00:00Z",
    user: dummyUsers[4],
    event: dummyEvents[0],
  },
]
